rvm:
  - 1.9.3
  - 2.0.0
  - 2.1

branches:
  only:
    - master

notifications:
  irc:
    channels:
      - "chat.freenode.net#chefspec"
    use_notice: true
    skip_join: true
    template:
      - "%{message} (%{author}): %{build_url}"

bundler_args: --jobs 7

gemfile:
  - gemfiles/chef-11.12.0.gemfile
  - gemfiles/chef-master.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - gemfile: gemfiles/chef-master.gemfile
