#
# Cookbook Name:: site-cookbooks/kn_deployer
# Recipe:: default
#
# Copyright (C) 2014, Cuck FD
#
# All rights reserved - Do Not Redistribute
#

log "Starting users accounts creation and configurations..."

log "Creating server maintainer(s) account(s)..."
include_recipe "users::sysadmins"

log "Creating webapp maintainer account..."
deployer = data_bag_item('deployers', node[:server_ingredients][:webapp_maintainer])

users_manage "deployer" do
  data_bag "deployers"
  group_name "deployer"
  group_id 2000
end

%w(www-data adm).each do |group|
  group group do
    action :modify
    members ['deployer', 'sysadmin']
    append true
  end
end

# Add sysadmin and deployer account to sudoers
%W(sysadmin #{deployer['username']}).each do |user|
  sudo user do
    user      user
    group     user
    commands  ['ALL']
    host      'ALL'
    nopasswd  true
  end

  execute "generate user keygen" do
    user user
    command "ssh-keygen -t dsa -f /home/#{user}/.ssh/id_dsa -N '' -C 'Keygen generated by using Chef #{DateTime.now.strftime('%Y-%m-%d %H:%M:%S')}'"
    creates "/home/#{user}/.ssh/id_dsa"
    action :run
  end
end

template "#{deployer['home']}/.ssh/authorized_keys" do
  source    'authorized_keys.erb'
  owner   deployer['username']
  group   'deployer'
  mode    '0600'
  variables ssh_keys: deployer['ssh_keys']
end


log "Users accounts created"
